# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScrollViewTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ScrollViewTest
  pod 'AFNetworking'
  pod 'WRNavigationBar'
  pod 'YYKit'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'

  target 'ScrollViewTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScrollViewTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
